Feature/6 store create
Ttottoga/BE pull request #15
Opened 2024-01-24 02:07 UTC by 5nam

Store 생성 기능 구현했습니다. 테스트용 데이터를 생성하기 위한 버전이라, 테스트 코드는 따로 작성하지 않았습니다.

추후에 상점 페이지가 만들어진다면, 그때 보완하겠습니다.

코드 보시고 리뷰 남겨주시면 감사하겠습니다 :)

2024-01-24 13:10 UTC, nicehcy2 approved these changes

2024-01-24 15:23 UTC, YeowonKIM requested changes

2024-01-24 15:23 UTC, YeowonKIM commented on src/main/resources/application-h2.properties
> +#h2 console ??? ? ?? ??
저희 properties에 이후 정보 더 추가하기 전에 gitignore 하는 게 좋을 것 같습니다!

2024-01-24 15:23 UTC, YeowonKIM commented on src/main/java/com/umc/ttg/domain/store/api/StoreController.java
> +        Store store = new Store(createStoreRequest);
controller에서 Http요청 Dto로 받는 부분을 service에서 로직 처리(객체 생성하는 부분) 하고, controller에서는 호출만 하는 게 둘의 구분 상 더 적합하다고 생각했습니다. 이 부분 어떻게 생각하시는지 궁금합니다.

2024-01-24 15:23 UTC, YeowonKIM commented on src/main/java/com/umc/ttg/domain/store/application/StoreCommandServiceImpl.java
> +public class StoreCommandServiceImpl implements StoreCommandService {
상정 관련 기능들 인터페이스 써서 구현하는 부분 좋다고 생각합니다 👍

2024-01-24 15:23 UTC, YeowonKIM commented on src/main/java/com/umc/ttg/domain/store/dto/CreateStoreRequest.java
> +public class CreateStoreRequest {
자바 명명규칙 상 클래스명이 동사라 메서드명처럼 느껴져서, 명사로 바꾸는 것이 좋을 것 같습니다.
코드 상에서 Dto 역할로 사용하신 거 같아 StoreRequestDto 이런 식으로 바꾸는 건 어떠신가요??

2024-01-24 15:23 UTC, YeowonKIM commented on src/main/java/com/umc/ttg/domain/store/dto/CreateStoreResponse.java
> +public class CreateStoreResponse {
위와 동일한 이유로 명사로 바꾸는 것이 좋을 것 같다고 생각합니다. 
ex. StoreResponseDto

2024-01-24 15:23 UTC, YeowonKIM commented on src/main/java/com/umc/ttg/domain/store/dto/converter/StoreConverter.java
> +    public static String toS3ImageLink(MultipartFile multipartFile) {
자바 명명 규칙상 메서드명은 동사로 시작해야 하므로, 바꾸는 게 좋지 않을까 생각합니다.
'to'를 사용해서 의미상 전달하고 싶으신 부분을 예를 들어 convertToS3ImageLink 이런 식은 어떠신가요??

2024-01-24 15:23 UTC, YeowonKIM commented on src/main/java/com/umc/ttg/domain/store/dto/converter/StoreConverter.java
> +    public static CreateStoreResponse toCreateStoreResponse(Long storeId) {
동일 이유로 동사로 시작하도록 바꾸는 게 좋지 않을까 생각합니다.

2024-01-24 15:33 UTC, YeowonKIM commented
로직이나 전체적으로 잘 작성하신 것 같습니다 👍
명명규칙이나 이런 부분 맞추면 좋을 것 같아 몇 가지 리뷰 남겼는데,
그 부분 확인해보시고 괜찮으시면 수정한 뒤 merge하면 좋을 것 같습니다 고생 많으셨습니다!

2024-01-25 03:10 UTC, 5nam commented on src/main/resources/application-h2.properties
> +#h2 console ??? ? ?? ??
h2 설정이라 gitignore 에 등록안했습니다..! DB 연결할 때는 gitignore 에 등록할 예정인데 h2 필요할까요?

2024-01-25 04:06 UTC, 5nam commented on src/main/java/com/umc/ttg/domain/store/api/StoreController.java
> +        Store store = new Store(createStoreRequest);
우선, 좋은 피드백 정말 감사드립니다 :) 

저는 Controller 단에서는 Request DTO 를 통해서 요청 데이터를 넘겨받고, Service 단에서 처리할 때 필요한 데이터만 넘기는 것이 적합하다고 생각했습니다.

1. Service 에서는 비즈니스 로직에 관련된 것만 수행해야 한다고 생각하였습니다. Store 생성에서 필요한 데이터는 Store 객체라고 생각했기 때문에, Controller 에서는 요청 데이터를 받아서 가공하여 넘기는 역할을 해주는 것이 적합하다고 생각했습니다.
2. 테스트 코드 작성 시, **Request DTO 를 생성-Request DTO 로 Store 객체 생성-Service 로직 수행** 보다는 **Store 객체 생성-Service 로직 수행** 이 과정이 테스트할 때 적합하다고 생각했습니다.

Controller 는 요청 데이터를 받아서, 여러 검증을 거쳐서 필요한 로직을 호출하면서 필요한 데이터만을 넘겨주는 역할이라고 생각했고, Service 는 순수하게 비즈니스 로직만 수행해야 한다고 생각했습니다!

2024-01-25 04:06 UTC, 5nam commented on src/main/java/com/umc/ttg/domain/store/dto/CreateStoreRequest.java
> +public class CreateStoreRequest {
좋은 피드백 감사합니다! 반영하겠습니다👍

2024-01-25 04:06 UTC, 5nam commented on src/main/java/com/umc/ttg/domain/store/dto/CreateStoreResponse.java
> +public class CreateStoreResponse {
좋은 피드백 감사합니다! 반영하겠습니다👍

2024-01-25 04:07 UTC, 5nam commented on src/main/java/com/umc/ttg/domain/store/dto/converter/StoreConverter.java
> +    public static String toS3ImageLink(MultipartFile multipartFile) {
명확한 함수명을 짓는게 어렵다고 느껴졌었는데, 좋은 피드백 정말 감사합니다!

2024-01-25 06:31 UTC, g00hyun approved these changes

2024-01-25 23:29 UTC, YeowonKIM commented on src/main/resources/application-h2.properties
> +#h2 console ??? ? ?? ??
넵 말씀하신 대로 현재 보안 상 문제 보다는 미리 설정해 두면 좋을 것 같아 말씀 드렸습니다!
제가 다음 pr 보낼 때 설정해 둘까요?

2024-01-25 23:49 UTC, YeowonKIM commented on src/main/java/com/umc/ttg/domain/store/api/StoreController.java
> +        Store store = new Store(createStoreRequest);
좋은 의견 감사합니다 :)

컨트롤러는 들어오는 HTTP 요청을 처리하고 입력 데이터를 검증하고 다음 필요한 정보만 서비스 계층에 전달하는 일을 담당해야 한다고 생각합니다.

루아님 말씀대로 서비스 계층은 애플리케이션 도메인과 관련된 비즈니스 로직을 수행하는 데 집중해야 한다고 생각했고, 루아님과 제가 어디까지 비즈니스 로직인지 판단한 게 다른 것 같아요!

이런 관점에서 저희 서비스에 맞춰 생각해 본다면, 저는 상점 생성부터 비즈니스 로직이라고 생각해서 컨트롤러에 있다는 게 어색하다고 느껴졌습니다. 요청 데이터로 스토어 개설하는 것이 비스니스 요소 중 하나라고 생각했습니다. 그래서 컨트롤러가 객체를 생성하면서 데이터를 가공하는 것까지 보다는 검증까지가 적절한 역할 분담이지 않을까 생각했습니다.

테스트 부분의 request 내용도 객체처럼 mock으로 생성해서 하면 크게 문제 없을 걸로 생각했습니다.

그렇지만 루아님 의견도 들어보고 좋은 의견이라고 생각했고, 확인하시면 논의해 보고 반영하면 좋을 것 같습니다 ☺️

2024-01-26 04:40 UTC, 5nam commented on src/main/resources/application-h2.properties
> +#h2 console ??? ? ?? ??
네넵! 좋습니다! 어차피 h2 설정은 다같이 해두면 좋은거라 그대로 올리는 편이 좋을듯합니다!

2024-01-26 04:47 UTC, 5nam commented on src/main/java/com/umc/ttg/domain/store/api/StoreController.java
> +        Store store = new Store(createStoreRequest);
오오 제가 Mock 써 본 적이 없어서, 거기까지 생각하지 못했던 거 같습니다!

그리고 여원님 말씀처럼 상점 생성이 비즈니스 로직에 포함되어야 하는 것이 맞게 느껴지네요! 의미를 중점적으로 생각했어야 했는데, 제가 필요한 데이터에만 집중했네요!

여원님이 말씀하신대로 반영하는 것이 맞는듯합니다! 반영해서 다시 올리겠습니다👍 좋은 피드백 정말 감사드려요 ㅎㅎ

2024-01-27 12:24 UTC, YeowonKIM approved these changes

2024-01-27 12:26 UTC, merged