:sparkles: kakao oauth login 구현
Ttottoga/BE pull request #67
Opened 2024-02-12 10:22 UTC by g00hyun

- [x] Cors 설정
- [x] Csrf disable
- [x] session 미사용
- [ ] 권한 설정 -> 현재는 아무나 권한 허용
- [x] kakao oauth2login 설정
- [ ] naver oauth2login 설정
- [ ] 권한 없는 사용자 error 핸들링 처리 -> 임시 페이지(rule지킨 error handling 필요
- [x] jwtFilter 설정

2024-02-12 10:46 UTC, YeowonKIM commented
우선 구현하느라 고생 많으셨습니다 👍
전반적으로 print로 찍고 있는 부분, 에러처리, WebSecurityConfig 설정 등 한 번 더 검토해 보시면 좋을 것 같다고 생각이 들었습니다!
특히 에러처리가 되어 있지 않아 에러 발생 시 어느 부분인지 확인하기가 어려워 보여서, 이 부분 우선적으로 수정하시면 더 좋을 것 같습니다.

2024-02-12 11:08 UTC, 5nam reviewed
리뷰 남겼습니다. 수고 많으셨습니다!

2024-02-12 11:08 UTC, 5nam commented on src/main/java/com/umc/ttg/domain/member/application/OAuth2MemberServiceImpl.java
> +            System.out.println(new ObjectMapper().writeValueAsString(oAuth2User.getAttributes()));
이 부분들은 log 로 사용하시는게 좋을듯 합니다!
`@Slf4j` class 위에 추가하고 log.info 등으로 이용하시면 됩니다.

2024-02-12 11:08 UTC, 5nam commented on src/main/java/com/umc/ttg/domain/member/application/OAuth2MemberServiceImpl.java
> +        try {
확인용 코드라면 따로 함수로 빼서 만드시는 편(try-catch)이 함수 분리에 도움이 될 듯 합니다!

2024-02-12 11:08 UTC, 5nam commented on src/main/java/com/umc/ttg/domain/member/application/OAuth2MemberServiceImpl.java
> +            Map<String, Object> properties = (Map<String, Object>) oAuth2User.getAttributes().get("properties");
여기 아래 부분도 함수로 분리하면 더 깔끔해질 것 같습니다! kakaoLoadUser/naverLoadUser 이렇게 분리하면 좋을듯 합니다.

2024-02-12 11:08 UTC, 5nam commented on src/main/java/com/umc/ttg/domain/member/application/OAuth2MemberServiceImpl.java
> +
이쯤에 member 가 존재하는 member 인지 확인하는 로직이 있으면 좋을듯 합니다.
userId 가 만약 DB 에 존재하는 회원이라면, 아래 로직들을 실행할 필요없이 바로 로그인으로 넘어가면 되기 때문에 여기에 
```
if(memberService.findMemberByUsername(member.getName()) == null) {
            memberRepository.save(member);
}
```
이 로직이 들어가면 좋을듯 합니다. 위의 검정 로직을 함수로 분리해놓으면 깔끔할 것 같습니다.

2024-02-12 11:08 UTC, 5nam commented on src/main/java/com/umc/ttg/global/auth/jwt/JwtAuthenticationFilter.java
> +                System.out.println("not have token!!!!");
여기도 log 로 바꾸시면 좋을듯 합니다!

2024-02-12 11:22 UTC, YeowonKIM requested changes

2024-02-12 11:22 UTC, YeowonKIM commented on src/main/java/com/umc/ttg/global/auth/jwt/JwtAuthenticationFilter.java
> +                System.out.println("not have userId!!!!");
전반적으로 print로 찍는 부분 변경하면 좋을 것 같습니다.
로깅 관련 자료 참고하시면 좋을 것 같습니다!

2024-02-12 11:22 UTC, YeowonKIM commented on src/main/java/com/umc/ttg/domain/member/application/MemberServiceImpl.java
> +        Member user = null;
member와 user가 혼용되고 있어서, 저희 초기 엔티티 설계대로 member로 통일하는 게 좋을 것 같습니다.

2024-02-12 11:22 UTC, YeowonKIM commented on src/main/java/com/umc/ttg/domain/member/application/OAuth2MemberServiceImpl.java
> +        Member member = null;
변수 초기화 하지만으면 디폴트가 null인데, 전체적으로 null로 명시적으로 초기화 한 이유가 있으신지 궁금합니다.

2024-02-13 16:04 UTC, g00hyun commented on src/main/java/com/umc/ttg/domain/member/application/OAuth2MemberServiceImpl.java
> +            System.out.println(new ObjectMapper().writeValueAsString(oAuth2User.getAttributes()));
자세한 피드백 감사합니다.
해당 부분 수정 완료했습니다.

2024-02-13 16:05 UTC, g00hyun commented on src/main/java/com/umc/ttg/domain/member/application/OAuth2MemberServiceImpl.java
> +        try {
로직 분리가 조금 필요할거같네요! 우선은 기능 구현이 잘 동작되는거 확인 이후에 바로 적용해보도록 할게요!

2024-02-13 16:05 UTC, g00hyun commented on src/main/java/com/umc/ttg/domain/member/application/OAuth2MemberServiceImpl.java
> +            Map<String, Object> properties = (Map<String, Object>) oAuth2User.getAttributes().get("properties");
:)

2024-02-13 16:06 UTC, g00hyun commented on src/main/java/com/umc/ttg/domain/member/application/OAuth2MemberServiceImpl.java
> +
해당 부분 로직도 추가해놓도록 하겠습니다

2024-02-13 16:06 UTC, g00hyun commented on src/main/java/com/umc/ttg/global/auth/jwt/JwtAuthenticationFilter.java
> +                System.out.println("not have userId!!!!");
자세한 피드백 감사합니다.
해당 부분 수정완료했습니다.

2024-02-13 16:07 UTC, g00hyun commented on src/main/java/com/umc/ttg/domain/member/application/MemberServiceImpl.java
> +        Member user = null;
이 부분을 놓치고있었네요. 기능 동작 정상적으로 되는지 확인 후 바로 고치도록하겠습니다

2024-02-13 16:08 UTC, g00hyun commented on src/main/java/com/umc/ttg/domain/member/application/OAuth2MemberServiceImpl.java
> +        Member member = null;
이전에 코딩습관인거같은데 좋은 작성룰이 아니라면 수정하도록 할게요!

2024-02-14 05:44 UTC, 5nam approved these changes

2024-02-14 05:44 UTC, 5nam commented on src/main/java/com/umc/ttg/domain/member/application/MemberServiceImpl.java
> +        return memberRepository.findByName(username).orElse(null);
여기서 못 찾았을 때 Member 가 없으면 null 을 반환하는 이유가 있을까요?
만약, 다른 의도가 없으신 `.orElseThrow(() -> new StoreHandler(ResponseCode.NOT_FOUND_MEMBER)); `처럼 에러 핸들러로 처리하는 것이 좋을듯 합니다!

2024-02-14 07:52 UTC, YeowonKIM approved these changes

2024-02-14 07:52 UTC, YeowonKIM commented on src/main/java/com/umc/ttg/global/common/ResponseCode.java
> +    // Token Error
에러 처리 추가하신 거 좋습니다👍

2024-02-14 08:42 UTC, g00hyun commented on src/main/java/com/umc/ttg/domain/member/application/MemberServiceImpl.java
> +        Member user = null;
네이밍 혼용해서 사용하는 부분 수정 완료했습니다

2024-02-14 08:44 UTC, g00hyun commented on src/main/java/com/umc/ttg/domain/member/application/MemberServiceImpl.java
> +        return memberRepository.findByName(username).orElse(null);
확인했습니다! 먼저 병합 후 에러핸들링에 대한 디테일 수정하도록할게요!

2024-02-14 08:44 UTC, merged